[build]
  command = "remix build"
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "remix dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[build.environment]
  SESSION_SECRET = "grit-construction-admin-session-secret"
  NODE_ENV = "production"
  ADMIN_USERNAME = "admin-grit-construction"
  ADMIN_PASSWORD_HASH = "$2a$10$1D0eQDyE3G3wLoU2L2i3De2l0Vyi9F27hiOLl/fSt8DReuR00mUSC"
  MY_AWS_REGION = "us-east-2"
  AWS_BUCKET_NAME = "grit-construction-gallery" 